// Faqs
export const Faqs = [
    {
      question: "How do I purchase a bus ticket online?",
      answer:
        "To purchase a bus ticket online, visit our website or mobile app, select your desired route and travel date, choose the available bus, and complete the payment process using your preferred payment method. You will receive a digital ticket via email or SMS.",
    },
    {
      question: "Can I track the location of my bus in real-time?",
      answer:
        "Yes, our system allows you to track the location of your bus in real-time. Simply log in to your account on our website or mobile app, go to the 'Track My Bus' section, and enter your ticket number or bus details to view its current location and estimated arrival time.",
    },
    {
      question: "What should I do if I miss my bus?",
      answer:
        "If you miss your bus, please contact our customer support team as soon as possible. Depending on availability and the terms and conditions of your ticket, we may be able to rebook you on the next available bus or offer a partial refund.",
    },
    {
      question: "Is it safe to make payments online for bus tickets?",
      answer:
        "Yes, making payments online through our system is safe and secure. We use advanced encryption technologies and comply with international security standards to ensure that your personal and payment information is protected.",
    },
    {
      question: "How can I cancel or change my ticket booking?",
      answer:
        "To cancel or change your ticket booking, log in to your account on our website or mobile app, go to the 'My Bookings' section, select the ticket you wish to cancel or change, and follow the prompts. Please note that cancellations and changes are subject to our terms and conditions, and additional fees may apply.",
    },
    {
      question: "What should I do if I lose my digital ticket?",
      answer:
        "If you lose your digital ticket, you can retrieve it by logging into your account on our website or mobile app. Go to the 'My Bookings' section to view and re-send your ticket details.",
    },
    {
      question: "Can I bring luggage on the bus?",
      answer:
        "Yes, you can bring luggage on the bus. Each passenger is allowed one piece of checked luggage and one carry-on bag. Additional luggage may incur extra fees, depending on the bus company’s policies.",
    },
  ];

  export const BusPark = [
    "Kimironko",
    "Nyabugogo",
    "Remera",
    "Nyamirambo",
    "Gikondo",
    "Kagugu",
    "Busanza",
    "Kabuga",
    "Nyanza",
    "Kinyinya",
  ];

  export const BusStops = [
    "Biryogo",
    "Busanza",
    "Downtown",
    "Gikondo",
    "Gisozi",
    "Kabeza",
    "Kabuga",
    "Kagugu",
    "Karama",
    "Kimironko",
    "Kimisagara",
    "Kimisange",
    "Kinyinya",
    "Kiyovu",
    "Masaka",
    "Mulindi",
    "Ndera",
    "Nyanza",
    "Nyabugogo",
    "Nyamirambo",
    "Nyarugunga",
    "Rebero",
    "Remera",
    "Rusororo",
    "Ruyenzi",
    "Zindiro",
  ];
  export const busStopsImages = [
    {location: 'Biryogo', image: "https://lh5.googleusercontent.com/p/AF1QipPw_XoLpIJMT5BLSZTUKrpBKyaxX9fjF17KdvHT=w493-h240-k-no"},
    {location: 'Busanza', image: "https://lh5.googleusercontent.com/p/AF1QipMSLg0YfKilbAs5o8FHVCaHecqcgrUmK-DoY82v=w426-h240-k-no"},
    {location: 'Downtown', image: "https://lh5.googleusercontent.com/p/AF1QipM8S2EYIv-Iiafnc1XgDbhdUJJCviONJg8aUmnn=w408-h258-k-no"},
    {location: 'Gisozi', image: "https://lh5.googleusercontent.com/p/AF1QipNfsGM3-1d_pwggvIGOvKp5SEA5rTbW2eUXVJTN=w408-h306-k-no"},
    {location: 'Kimironko', image: "https://live.staticflickr.com/675/21427387333_8449e95134_b.jpg"},
    {location: 'Nyabugogo', image: "https://lh5.googleusercontent.com/p/AF1QipOyBjBbEsPO01Ki3Nc0My5U1FdQ5mGe3Et33jTj=w408-h306-k-no"},
    {location: 'Masaka', image: "https://cf.bstatic.com/xdata/images/hotel/max1024x768/94413796.webp?k=b6aa3a8338b15bf08f772fd90a0d6bec1444c5e4002ec6eb719686f9ec4945ca&o="},
    {location: 'Remera', image: "https://lh5.googleusercontent.com/p/AF1QipOmFvYWNkLZqRbL1W80pi9USHzJuINWIQgVCB_9=w408-h302-k-no"},
    {location: 'Ruyenzi', image: "https://lh5.googleusercontent.com/p/AF1QipMsW9FnkwUnYRlcDa8uccY3fsbNIzF36wZp8PsL=w408-h884-k-no"},
    {location: 'Nyamirambo', image: "https://lh5.googleusercontent.com/p/AF1QipMLjn4wPiJuX8wPDYKyJQW0WPytRYgfHQ4aMD-P=w408-h278-k-no"},
    {location: 'Kiyovu', image: "https://lh5.googleusercontent.com/p/AF1QipO-EDGjh_3JDTxFgTG7b7m68RFYEJWFe_Y1MKet=w426-h240-k-no"},
    {location: "Gikondo", image: "https://i0.wp.com/panorama.rw/wp-content/uploads/2023/11/Gikondo1.jpg?resize=880%2C587&ssl=1"},
    {location: "Kabeza", image: "https://farm1.staticflickr.com/226/463793578_7ecb2dcf57.jpg"},
    {location: "Kagugu", image: "https://i.pinimg.com/564x/01/fa/97/01fa97b13f914223cff254c90892602a.jpg"},
    {location: "Kabuga", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcST3DViauurVoFTDKY91FkNV2bQQHpPTvF6_A&s"},
    {location: "Karama", image: "https://www.ktpress.rw/wp-content/uploads/2019/07/Karama-3.jpg"},
    {location: "Kimisagara", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/Road_in_Kimisagara.jpg/2560px-Road_in_Kimisagara.jpg"},
    {location: "Kimisange", image: "https://www.kigalitoday.com/IMG/jpg/kimisange.jpg"},
    {location: "Kinyinya", image: "https://greencitykigali.org/wp-content/uploads/commercial-areas-400x400.jpg"},
    {location: "Ndera", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSEb0sjVTsLGpcwtrIXgPvbBGhIkYBUiI5Lrwr3EBdyaSBhqwwcc_qjO1qzCWzxxWXdyP4&usqp=CAU"},
    {location: "Nyanza", image: "https://live.staticflickr.com/65535/53321287375_dcff648424_b.jpg"},
    {location: "Nyarugunga", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQB52T-c34bgfBFfm7XBoBbpECIKuaxE95kHw&s"},
    {location: "Rebero", image: "https://livinginkigali.com/wp-content/uploads/2023/07/Rebero2.jpg"},
    {location: "Rusororo", image: "https://farm8.static.flickr.com/7860/46597325465_634f597065.jpg"},
    {location: "Zindiro", image: "https://i.ytimg.com/vi/l9WP4u3LegE/maxresdefault.jpg"},
  ]

  export const KigaliBusJourney = [
    {
      id: "JF937H950-248802-DNDNJ",
      plateNumber: "RAC843KG",
      numberOfSeats: 35,
      from: "Kimironko",
      to: "Zindiro",
      busType: "Royal",
      departureAt: "8:00 am",
      arrivalTime: "8:30 am",
      price: "217",
      stops: ["Kimironko Taxi Park", "Kwa Mushimire", "Zindiro", "Kwa Nayinzira", "AZAM Roundabout", "ALU"],
      RouteId: "307",
    },
    {
      id: "JF937H950-248803-DNDNK",
      plateNumber: "RAC844KG",
      numberOfSeats: 35,
      from: "Kimironko",
      to: "Downtown",
      busType: "Royal",
      departureAt: "9:30 am",
      arrivalTime: "10:00 am",
      price: "300",
      stops: ["Kimironko Taxi Park","Stadium","chez lando","Kimihurura","Convetion center","Kigali City Tower"],
      RouteId: "302",
    },
    {
      id: "JF937H950-248804-DNDNL",
      plateNumber: "RAC845KG",
      numberOfSeats: 35,
      from: "Nyanza",
      to: "Downtown",
      busType: "Kigali Bus Service",
      departureAt: "10:15 am",
      arrivalTime: "11:00 am",
      price: "277",
      stops: ["Nyanza Taxi Park","Gatenga Magerwa","Down Town Taxi Park"],
      RouteId: "203",
    },
    {
      id: "JF937H950-248805-DNDNM",
      plateNumber: "RAC846KG",
      numberOfSeats: 35,
      from: "Nyanza",
      to: "Nyabugogo",
      busType: "Royal",
      departureAt: "11:15 am",
      arrivalTime: "12:00 pm",
      price: "320",
      stops: ["Nyanza Taxi Park","Zion Temple" ,"Rwandex", "Kinamba", "Nyabugogo Taxi Park"],
      RouteId: "204",
    },
    {
      id: "JF937H950-248806-DNDNN",
      plateNumber: "RAC847KG",
      numberOfSeats: 35,
      from: "Remera",
      to: "Gikondo",
      busType: "Kigali Bus Service",
      departureAt: "12:15 pm",
      arrivalTime: "12:45 pm",
      price: "310",
      stops: ["Remera Taxi Park", "Sonatubes", "Rwandex", "Gikondo (Nyenyeli)"],
      RouteId: "109",
    },
    {
      id: "JF937H950-248808-DNDNP",
      plateNumber: "RAC849KG",
      numberOfSeats: 35,
      from: "Busanza",
      to: "Remera",
      busType: "Kigali Bus Service",
      departureAt: "2:00 pm",
      arrivalTime: "2:40 pm",
      price: "165",
      stops: ["Busanza", "Rubilizi", "Kabeza", "Remera Taxi Park"],
      RouteId: "113",
    },
    {
      id: "JF937H950-248809-DNDNQ",
      plateNumber: "RAC850KG",
      numberOfSeats: 35,
      from: "Nyamirambo",
      to: "Nyabugogo",
      busType: "Royal",
      departureAt: "3:00 pm",
      arrivalTime: "3:30 pm",
      price: "220",
      stops: ["Nyamirambo (Ryanyuma)", "Kimisagara", "Nyabugogo Taxi Park"],
      RouteId: "402",
    },
    {
      id: "JF937H950-248810-DNDNR",
      plateNumber: "RAC851KG",
      numberOfSeats: 35,
      from: "Kagugu",
      to: "Nyabugogo",
      busType: "Kigali Bus Service",
      departureAt: "4:00 pm",
      arrivalTime: "4:30 pm",
      price: "216",
      stops: ["Kagugu", "Bel Etoile", "ULK", "Kinamba", "Nyabugogo Taxi Park"],
      RouteId: "311",
    },
    {
      id: "JF937H950-248807-DNDNO",
      plateNumber: "RAC848KG",
      numberOfSeats: 35,
      from: "Gikondo",
      to: "Nyabugogo",
      busType: "Royal",
      departureAt: "1:00 pm",
      arrivalTime: "2:10 pm",
      price: "271",
      stops: ["Gikondo (Nyenyeli)", "Rwampara", "Rugunga", "Kinamba", "Nyabugogo Taxi Park"],
      RouteId: "206",
    },
    {
      id: "JF937H950-248814-DNDNV",
      plateNumber: "RAC855KG",
      numberOfSeats: 35,
      from: "Kabuga",
      to: "Nyabugogo",
      busType: "Kigali Bus Service",
      departureAt: "8:00 pm",
      arrivalTime: "9:45 pm",
      price: "517",
      stops: ["Kabuga Taxi Park", "Mulindi", "Remera", "Sonatubes", "Rwandex", "Nyabugogo Taxi Park"],
      RouteId: "102",
    },
    {
      id: "JF937H950-248815-DNDNW",
      plateNumber: "RAC856KG",
      numberOfSeats: 35,
      from: "Kabuga",
      to: "Kimironko",
      busType: "Royal",
      departureAt: "9:00 pm",
      arrivalTime: "10:20 pm",
      price: "397",
      stops: ["Kimironko Taxi Park", "Kigali Parent School", "12", "15", "Mulindi", "19", "Kabuga  Taxi Park"],
      RouteId: "325",
    },
    {
      id: "JF937H950-248816-DNDNX",
      plateNumber: "RAC857KG",
      numberOfSeats: 35,
      from: "Remera",
      to: "Nyabugogo",
      busType: "Kigali Bus Service",
      departureAt: "10:00 pm",
      arrivalTime: "10:30 pm",
      price: "253",
      stops: ["Remera Taxi Park", "Chez Lando" ,"Kacyiru", "Nyabugogo Taxi Park"],
      RouteId: "105",
    },
    {
      id: "JF937H950-248817-DNDNY",
      plateNumber: "RAC858KG",
      numberOfSeats: 35,
      from: "Remera",
      to: "Masaka",
      busType: "Royal",
      departureAt: "11:00 pm",
      arrivalTime: "11:30 pm",
      price: "273",
      stops: ["Remera Taxi Park", "12", "15", "Mulindi", "19", "Masaka"],
      RouteId: "107",
    },
    {
      id: "JF937H950-248818-DNDNZ",
      plateNumber: "RAC859KG",
      numberOfSeats: 35,
      from: "Kimironko",
      to: "Masaka",
      busType: "Kigali Bus Service",
      departureAt: "12:00 am",
      arrivalTime: "12:30 am",
      price: "253",
      stops: ["Kimironko Taxi Park", "15", "Mulindi", "19", "Masaka"],
      RouteId: "322",
    },
    {
      id: "JF937H950-248819-DNDOA",
      plateNumber: "RAC860KG",
      numberOfSeats: 35,
      from: "Kinyinya",
      to: "Downtown",
      busType: "Kigali Bus Service",
      departureAt: "7:30 am",
      arrivalTime: "8:15 am",
      price: "244",
      stops: ["Kinyinya", "UTEXRWA", "Kinamba", "Down Town Taxi Park" ],
      RouteId: "317",
    },
    {
      id: "JF937H950-248820-DNDOB",
      plateNumber: "RAC861KG",
      numberOfSeats: 35,
      from: "Kimironko",
      to: "Nyabugogo",
      busType: "Kigali Bus Service",
      departureAt: "8:30 am",
      arrivalTime: "9:00 am",
      price: "310",
      stops: ["Kimironko taxi park", "Stadium", "Chez Lando", "Kacyiru", "Nyabugogo Taxi Park"],
      RouteId: "305",
    },
    {
      id: "JF937H950-248820-U229OB",
      plateNumber: "RAC861KG",
      numberOfSeats: 35,
      from: "Kimironko",
      to: "Nyabugogo",
      busType: "Kigali Bus Service",
      departureAt: "13:30 am",
      arrivalTime: "14:00 am",
      price: "242",
      stops: ["Nyabugogo Taxi Park", "Kinamba", "UTEXRWA", "Kibagabaga", "Kimironko Taxi Park"],
      RouteId: "314",
    },
  ]

  export const RouteIds = [
    {
      from: "Kimironko",
      to: "Zindiro",
      RouteId: "307",
    },
    {
      from: "Kimironko",
      to: "Downtown",
      RouteId: "302",
    },
    {
      from: "Nyanza",
      to: "Downtown",
      RouteId: "203",
    },
    {
      from: "Nyanza",
      to: "Nyabugogo",
      RouteId: "204",
    },
    {
      from: "Remera",
      to: "Gikondo",
      RouteId: "109",
    },
    {
      from: "Busanza",
      to: "Remera",
      RouteId: "113",
    },
    {
      from: "Nyamirambo",
      to: "Nyabugogo",
      RouteId: "402",
    },
    {
      from: "Kagugu",
      to: "Nyabugogo",
      RouteId: "311",
    },
    {
      from: "Gikondo",
      to: "Nyabugogo",
      RouteId: "206",
    },
    {
      from: "Kabuga",
      to: "Nyabugogo",
      RouteId: "102",
    },
    {
      from: "Kabuga",
      to: "Kimironko",
      RouteId: "325",
    },
    {
      from: "Remera",
      to: "Nyabugogo",
      RouteId: "105",
    },
    {
      from: "Remera",
      to: "Masaka",
      RouteId: "107",
    },
    {
      from: "Kimironko",
      to: "Masaka",
      RouteId: "322",
    },
    {
      from: "Kinyinya",
      to: "Downtown",
      RouteId: "317",
    },
    {
      from: "Kimironko",
      to: "Nyabugogo",
      RouteId: "314",
    },
    {
      from: "Kimironko",
      to: "Nyabugogo",
      RouteId: "305",
    },
  ]
  export const BusStations = [
    "Kigali",
    "Huye",
    "Musanze",
    "Nyanza"
  ];

  export const BusStationsImages = [
    {location: 'Kigali', image: "https://www.safarisrwandasafari.com/wp-content/uploads/2022/09/kigali-city..-1.jpg"},
    {location: 'Huye', image: "https://c1.staticflickr.com/2/1712/25836586392_a2372e9e95_b.jpg"},
    {location: 'Musanze', image: "https://media.istockphoto.com/id/1471123952/photo/a-man-who-works-for-musanze-bus-station.jpg?s=612x612&w=0&k=20&c=aOn8NJditzTGaRbRhS_lOQQyW8YCym3-JDAJCaziSxk="},
    {location: 'Nyanza', image: "https://www.nyungweforestnationalpark.org/wp-content/uploads/2022/05/Kings-Palace-Nyanza.jpg"},

  ];

  export const Companies = [
    {
      name: "Volcano",
      logo: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT1iszThteThGMm9XkwiKkYz_F0u3Z0pPfmALunl6MqNSUgV68RgdKfrgi_UADwfujqRAE&usqp=CAU",
      email: "volcano@gmail.com"
    },
    {
      name: "Horizon",
      logo: "https://horizonexpress.rw/wp-content/uploads/2022/02/Horizon_Express_Logo_Modified_page-0001__1_-removebg-preview.png",
      email: "Horizon@gmail.com"
    },

  ]
